version: "3.7"


networks:
  server:
  k6:
  grafana:
  influxdb:

services:
  server:
    build: .
    container_name: sample-server
    ports:
      - "8080:8080"
  influxdb:
    image: bitnami/influxdb:2.7.10
    container_name: influxdb
    restart: always
    ports:
      - "8086:8086"
      - "8085:8088"
    volumes:
      - influxDb:/var/lib/influxdb2
    environment:
      - INFLUXDB_ADMIN_USER_PASSWORD=bitnami123
      - INFLUXDB_ADMIN_USER_TOKEN=admintoken123
      - INFLUXDB_HTTP_AUTH_ENABLED=false
      - INFLUXDB_DB=myk6db
  granafa:
    image: bitnami/grafana:latest
    restart: always
    depends_on:
      - influxdb
    ports:
      - "3000:3000"
    volumes:
      - ./data/grafana:/var/lib/grafana
  k6:
    image: grafana/k6:latest
    networks:
      - k6
    ports:
      - "6565:6565"
    depends_on:
      - influxdb
    environment:
      - K6_OUT=xk6-influxdb=http://influxdb:8086
      - K6_INFLUXDB_ORGANIZATION=primary
      - K6_INFLUXDB_BUCKET=primary
      - K6_INFLUXDB_INSECURE=true
      # NOTE: This is an Admin token, it's not suggested to use this configuration in production.
      # Instead, use a Token with restricted privileges.
      - K6_INFLUXDB_TOKEN=EEKpryGZk8pVDXmIuy484BKUxM5jOEDv7YNoeNZUbsNbpbPbP6kK_qY9Zsyw7zNnlZ7pHG16FYzNaqwLMBUz8g==
      - GOOS=darwin
    volumes:
      - ./scripts:/scripts
volumes:
  influxDb: {}
  grafana: {}